#include "LookupTable.h"
#include "addressing-modes/AddressingModeContainer.h"
#include "opcodes/OpcodeContainer.h"

std::unique_ptr<LookupTable> MakeLookupTable(AddressingModeContainer& addressingModes, OpcodeContainer& opcodes) {
  auto& addrM = addressingModes;
  auto table = std::make_unique<LookupTable>();

  *table = {
      {{&opcodes.brk, &addrM.imm, 7},        {&opcodes.ora, &addrM.izx, 6},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 3},        {&opcodes.ora, &addrM.zp0, 3},
       {&opcodes.asl, &addrM.zp0, 5},        {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.php, &addrM.imp, 3},
       {&opcodes.ora, &addrM.imm, 2},        {&opcodes.asl, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.nop, &addrM.imp, 4},        {&opcodes.ora, &addrM.abs, 4},        {&opcodes.asl, &addrM.abs, 6},
       {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.bpl, &addrM.rel, 2, true},  {&opcodes.ora, &addrM.izy, 5, true},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 4},
       {&opcodes.ora, &addrM.zpx, 4},        {&opcodes.asl, &addrM.zpx, 6},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.clc, &addrM.imp, 2},        {&opcodes.ora, &addrM.aby, 4, true},  {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.nop, &addrM.imp, 4, true},  {&opcodes.ora, &addrM.abx, 4, true},
       {&opcodes.asl, &addrM.abx, 7},        {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.jsr, &addrM.abs, 6},
       {&opcodes.andd, &addrM.izx, 6},       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},
       {&opcodes.bit, &addrM.zp0, 3},        {&opcodes.andd, &addrM.zp0, 3},       {&opcodes.rol, &addrM.zp0, 5},
       {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.plp, &addrM.imp, 4},        {&opcodes.andd, &addrM.imm, 2},
       {&opcodes.rol, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.bit, &addrM.abs, 4},
       {&opcodes.andd, &addrM.abs, 4},       {&opcodes.rol, &addrM.abs, 6},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.bmi, &addrM.rel, 2, true},  {&opcodes.andd, &addrM.izy, 5, true}, {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 4},        {&opcodes.andd, &addrM.zpx, 4},
       {&opcodes.rol, &addrM.zpx, 6},        {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.sec, &addrM.imp, 2},
       {&opcodes.andd, &addrM.aby, 4, true}, {&opcodes.nop, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 7},
       {&opcodes.nop, &addrM.imp, 4, true},  {&opcodes.andd, &addrM.abx, 4, true}, {&opcodes.rol, &addrM.abx, 7},
       {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.rti, &addrM.imp, 6},        {&opcodes.eor, &addrM.izx, 6},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 3},
       {&opcodes.eor, &addrM.zp0, 3},        {&opcodes.lsr, &addrM.zp0, 5},        {&opcodes.xxx, &addrM.imp, 5},
       {&opcodes.pha, &addrM.imp, 3},        {&opcodes.eor, &addrM.imm, 2},        {&opcodes.lsr, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.jmp, &addrM.abs, 3},        {&opcodes.eor, &addrM.abs, 4},
       {&opcodes.lsr, &addrM.abs, 6},        {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.bvc, &addrM.rel, 2, true},
       {&opcodes.eor, &addrM.izy, 5, true},  {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},
       {&opcodes.nop, &addrM.imp, 4},        {&opcodes.eor, &addrM.zpx, 4},        {&opcodes.lsr, &addrM.zpx, 6},
       {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.cli, &addrM.imp, 2},        {&opcodes.eor, &addrM.aby, 4, true},
       {&opcodes.nop, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.nop, &addrM.imp, 4, true},
       {&opcodes.eor, &addrM.abx, 4, true},  {&opcodes.lsr, &addrM.abx, 7},        {&opcodes.xxx, &addrM.imp, 7},
       {&opcodes.rts, &addrM.imp, 6},        {&opcodes.adc, &addrM.izx, 6},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 3},        {&opcodes.adc, &addrM.zp0, 3},
       {&opcodes.ror, &addrM.zp0, 5},        {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.pla, &addrM.imp, 4},
       {&opcodes.adc, &addrM.imm, 2},        {&opcodes.ror, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.jmp, &addrM.ind, 5},        {&opcodes.adc, &addrM.abs, 4},        {&opcodes.ror, &addrM.abs, 6},
       {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.bvs, &addrM.rel, 2, true},  {&opcodes.adc, &addrM.izy, 5, true},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 4},
       {&opcodes.adc, &addrM.zpx, 4},        {&opcodes.ror, &addrM.zpx, 6},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.sei, &addrM.imp, 2},        {&opcodes.adc, &addrM.aby, 4, true},  {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.nop, &addrM.imp, 4, true},  {&opcodes.adc, &addrM.abx, 4, true},
       {&opcodes.ror, &addrM.abx, 7},        {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.sta, &addrM.izx, 6},        {&opcodes.nop, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.sty, &addrM.zp0, 3},        {&opcodes.sta, &addrM.zp0, 3},        {&opcodes.stx, &addrM.zp0, 3},
       {&opcodes.xxx, &addrM.imp, 3},        {&opcodes.dey, &addrM.imp, 2},        {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.txa, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.sty, &addrM.abs, 4},
       {&opcodes.sta, &addrM.abs, 4},        {&opcodes.stx, &addrM.abs, 4},        {&opcodes.xxx, &addrM.imp, 4},
       {&opcodes.bcc, &addrM.rel, 2, true},  {&opcodes.sta, &addrM.izy, 6},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.sty, &addrM.zpx, 4},        {&opcodes.sta, &addrM.zpx, 4},
       {&opcodes.stx, &addrM.zpy, 4},        {&opcodes.xxx, &addrM.imp, 4},        {&opcodes.tya, &addrM.imp, 2},
       {&opcodes.sta, &addrM.aby, 5},        {&opcodes.txs, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 5},
       {&opcodes.nop, &addrM.imp, 5},        {&opcodes.sta, &addrM.abx, 5},        {&opcodes.xxx, &addrM.imp, 5},
       {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.ldy, &addrM.imm, 2},        {&opcodes.lda, &addrM.izx, 6},
       {&opcodes.ldx, &addrM.imm, 2},        {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.ldy, &addrM.zp0, 3},
       {&opcodes.lda, &addrM.zp0, 3},        {&opcodes.ldx, &addrM.zp0, 3},        {&opcodes.xxx, &addrM.imp, 3},
       {&opcodes.tay, &addrM.imp, 2},        {&opcodes.lda, &addrM.imm, 2},        {&opcodes.tax, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.ldy, &addrM.abs, 4},        {&opcodes.lda, &addrM.abs, 4},
       {&opcodes.ldx, &addrM.abs, 4},        {&opcodes.xxx, &addrM.imp, 4},        {&opcodes.bcs, &addrM.rel, 2, true},
       {&opcodes.lda, &addrM.izy, 5, true},  {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 5, true},
       {&opcodes.ldy, &addrM.zpx, 4},        {&opcodes.lda, &addrM.zpx, 4},        {&opcodes.ldx, &addrM.zpy, 4},
       {&opcodes.xxx, &addrM.imp, 4},        {&opcodes.clv, &addrM.imp, 2},        {&opcodes.lda, &addrM.aby, 4, true},
       {&opcodes.tsx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 4, true},  {&opcodes.ldy, &addrM.abx, 4, true},
       {&opcodes.lda, &addrM.abx, 4, true},  {&opcodes.ldx, &addrM.aby, 4, true},  {&opcodes.xxx, &addrM.imp, 4, true},
       {&opcodes.cpy, &addrM.imm, 2},        {&opcodes.cmp, &addrM.izx, 6},        {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.cpy, &addrM.zp0, 3},        {&opcodes.cmp, &addrM.zp0, 3},
       {&opcodes.dec, &addrM.zp0, 5},        {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.iny, &addrM.imp, 2},
       {&opcodes.cmp, &addrM.imm, 2},        {&opcodes.dex, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.cpy, &addrM.abs, 4},        {&opcodes.cmp, &addrM.abs, 4},        {&opcodes.dec, &addrM.abs, 6},
       {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.bne, &addrM.rel, 2, true},  {&opcodes.cmp, &addrM.izy, 5, true},
       {&opcodes.xxx, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 4},
       {&opcodes.cmp, &addrM.zpx, 4},        {&opcodes.dec, &addrM.zpx, 6},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.cld, &addrM.imp, 2},        {&opcodes.cmp, &addrM.aby, 4, true},  {&opcodes.nop, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.nop, &addrM.imp, 4, true},  {&opcodes.cmp, &addrM.abx, 4, true},
       {&opcodes.dec, &addrM.abx, 7},        {&opcodes.xxx, &addrM.imp, 7},        {&opcodes.cpx, &addrM.imm, 2},
       {&opcodes.sbc, &addrM.izx, 6},        {&opcodes.nop, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 8},
       {&opcodes.cpx, &addrM.zp0, 3},        {&opcodes.sbc, &addrM.zp0, 3},        {&opcodes.inc, &addrM.zp0, 5},
       {&opcodes.xxx, &addrM.imp, 5},        {&opcodes.inx, &addrM.imp, 2},        {&opcodes.sbc, &addrM.imm, 2},
       {&opcodes.nop, &addrM.imp, 2},        {&opcodes.sbc, &addrM.imp, 2},        {&opcodes.cpx, &addrM.abs, 4},
       {&opcodes.sbc, &addrM.abs, 4},        {&opcodes.inc, &addrM.abs, 6},        {&opcodes.xxx, &addrM.imp, 6},
       {&opcodes.beq, &addrM.rel, 2, true},  {&opcodes.sbc, &addrM.izy, 5, true},  {&opcodes.xxx, &addrM.imp, 2},
       {&opcodes.xxx, &addrM.imp, 8},        {&opcodes.nop, &addrM.imp, 4},        {&opcodes.sbc, &addrM.zpx, 4},
       {&opcodes.inc, &addrM.zpx, 6},        {&opcodes.xxx, &addrM.imp, 6},        {&opcodes.sed, &addrM.imp, 2},
       {&opcodes.sbc, &addrM.aby, 4, true},  {&opcodes.nop, &addrM.imp, 2},        {&opcodes.xxx, &addrM.imp, 7},
       {&opcodes.nop, &addrM.imp, 4, true},  {&opcodes.sbc, &addrM.abx, 4, true},  {&opcodes.inc, &addrM.abx, 7},
       {&opcodes.xxx, &addrM.imp, 7}}};
  return table;
}
