name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        type: [Release, Debug]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Updates package list
        run: sudo apt-get update

      - name: Installs dependencies
        run: xargs -a packages.txt sudo apt-get install -y

      - name: Prepare
        run: ./prepare.py --build-type=${{ matrix.type }}

      - name: Compute preset name
        run: echo "CMAKE_PRESET=conan-linux-x86_64-$(echo '${{ matrix.type }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Configure
        run: cmake --preset $CMAKE_PRESET

      - name: Build
        run: cmake --build --preset $CMAKE_PRESET --verbose

      - name: Test
        run: ctest --preset $CMAKE_PRESET

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}
          path: |
            build/${{ matrix.type }}/lib
            build/${{ matrix.type }}/bin
          retention-days: 5
