name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        type: [Release, Debug]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Updates package list
        run: sudo apt-get update

      - name: Installs dependencies
        run: xargs -a packages.txt sudo apt-get install -y

      - name: Configure
        run: cmake --preset ${{ matrix.type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.type }} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build/${{ matrix.type }}
        run: ctest --extra-verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}
          path: |
            build/${{ matrix.type }}/lib
            build/${{ matrix.type }}/bin
          retention-days: 5
