name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [Release, Debug, RelWithDebInfo, MinSizeRel]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install conan
        run: pip3 install conan

      - name: Updates package list
        run: sudo apt-get update

      - name: Installs dependencies
        run: |
          sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg libx11-xcb-dev \
            libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev \
            libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev \
            libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev \
            libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev \
            libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev \
            libxcb-util-dev \
            -y

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.type }}

      - name: Build
        run: cmake --build ./build/ --config ${{ matrix.type }} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --extra-verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.type }}
          path: |
            build/lib
            build/bin
          retention-days: 5
